name: Cmake Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PROJECT_NAME: Template

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build for Windows
              run: cmake . -G "MinGW Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
              
            - name: build
              run: cmake --build ./build
              
            - name: Archive production artifacts Windows
              uses: actions/upload-artifact@v3
              with:
                name: Build_Output
                path: |
                  build/${{env.PROJECT_NAME}}.exe
            
            
